name: Add Label based on Issue Input

on:
  issues:
    types: [opened, edited]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add label based on input
        uses: peter-evans/add-labels@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ github.event.issue.labels }}
          add: ${{ github.event.issue.labels }}
          remove: ''
          input: ${{ github.event.issue.body }}
          regex: 'Repository:\s*(.*)'
