name: Repo Contributor
on:
  # Schedule updates (once at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "📚 Documentation": ["README.md", "docs/**"],
              "💻 Code": ["source/**", "src/**"],
              "#️⃣ Others": ["*"]
            }
            user: keploy
